### ISSUE TITLE
better mimetype handling

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beaker-notebook-private#220]
https://github.com/twosigma/beaker-notebook-private/blob/master/kernel/base/src/main/java/com/twosigma/beaker/mimetype/MimeTypeManager.java#L38
instead of using a static method that just returns a map, the user should create and return a new instance of a mime type class.  call this class "MIMEContainer".  It should have subclasses Latex and HTML etc that fix the mime type in the constructor (they take just the value, compared to MIMEContainer that takes a value and a type).

that way in SerializeToString.java we can identify for sure what is a mime object instead of looking for a particular kind of map.

**Comment by fishera123** [comment]
will fix in #200
