### ISSUE TITLE
error from fresh repository

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beaker-notebook-private#232]
> ERROR in jquery-ui (bower component) Module not found: Error: Cannot resolve 'file' or 'directory' ./ui/jquery-ui.js

easily fixed by `rm -rf bower_components && bower install` but should not be needed.

**Comment by jszalek** [comment]
issue fixed on branch kuba/bowerFix1
PR: https://github.com/twosigma/beaker-notebook-private/pull/239
